version: 'version 3'


services:
  frontend:
    build: "./frontend"
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app"
    command: ["npm", "run", "dev"]
  backend:
    build: "./backend"
    ports:
      - "5000:5000"
    volumes:
      - "./backend:/app"
    command: ["npm", "run", "dev"]
